export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';

export const REQUEST_POSTS_LIST = 'REQUEST_POSTS_LIST';
export const RECEIVE_POSTS_LIST_SUCCESS = 'RECEIVE_POSTS_LIST_SUCCESS';
export const RECEIVE_POSTS_LIST_FAIL = 'RECEIVE_POSTS_LIST_FAIL';
